services:  
  
  conduktor-ctl:
    image: conduktor/conduktor-ctl:v0.3.3
    container_name: conduktor-ctl
    entrypoint: sleep infinity # override entry point to keep container up
    volumes:
      - ./:/self-service
    environment:
      CDK_BASE_URL: "http://conduktor-console:8080"
      CDK_API_KEY: "" # generate me from the UI for the demo, CLI also available

  postgresql:
    image: postgres:14
    hostname: postgresql
    volumes:
      - pg_data_ss:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "change_me"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  conduktor-console:
    container_name: conduktor-console
    image: conduktor/conduktor-console:1.30.0
    depends_on:
      - postgresql
      - redpanda-0
    ports:
      - "8080:8080"
    volumes:
      - conduktor_data_ss:/var/conduktor
    environment:
      CDK_DATABASE_URL: "postgres://conduktor:change_me@postgresql:5432/conduktor-console"
      CDK_ADMIN_EMAIL: "admin@conduktor.io"
      CDK_ADMIN_PASSWORD: "Adm!nP4ssw0rd"
      CDK_ORGANIZATION_NAME: "stu-conduktor-general"
      CDK_AUTH_LOCAL-USERS_0_EMAIL: "alice@conduktor.io"
      CDK_AUTH_LOCAL-USERS_0_PASSWORD: "alice-secret"
      CDK_AUTH_LOCAL-USERS_1_EMAIL: "bob@conduktor.io"
      CDK_AUTH_LOCAL-USERS_1_PASSWORD: "bob-secret"
      CDK_CLUSTERS_0_ID: "dev-cluster"
      CDK_CLUSTERS_0_NAME: "dev-cluster"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "redpanda-1:9093"
      CDK_CLUSTERS_0_SCHEMAREGISTRY_URL: "http://redpanda-1:18084"
      CDK_CLUSTERS_0_COLOR: "#E6702F"
      CDK_CLUSTERS_0_ICON: "elephant"
      CDK_CLUSTERS_1_ID: "prod-cluster"
      CDK_CLUSTERS_1_NAME: "prod-cluster"
      CDK_CLUSTERS_1_BOOTSTRAPSERVERS: "redpanda-0:9092"
      CDK_CLUSTERS_1_SCHEMAREGISTRY_URL: "http://redpanda-0:18081"
      CDK_CLUSTERS_1_COLOR: "#6A57C8"
      CDK_CLUSTERS_1_ICON: "kafka"
      CDK_MONITORING_CORTEX-URL: http://conduktor-monitoring:9009/
      CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-monitoring:9010/
      CDK_MONITORING_CALLBACK-URL: http://conduktor-console:8080/monitoring/api/
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:8080
  
  redpanda-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with eachother internally.
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.9
    container_name: redpanda-0
    volumes:
      - redpanda-0:/var/lib/redpanda/data
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s
      
  redpanda-1:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9093,external://0.0.0.0:19093
      - --advertise-kafka-addr internal://redpanda-1:9093,external://localhost:19093
      - --pandaproxy-addr internal://0.0.0.0:8083,external://0.0.0.0:18083
      - --advertise-pandaproxy-addr internal://redpanda-1:8083,external://localhost:18083
      - --schema-registry-addr internal://0.0.0.0:8084,external://0.0.0.0:18084
      - --rpc-addr redpanda-1:33146
      - --advertise-rpc-addr redpanda-1:33146
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.6
    container_name: redpanda-1
    volumes:
      - redpanda-1:/var/lib/redpanda/data
    ports:
      - 18083:18083
      - 18084:18084
      - 19093:19093
      - 19645:9645
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  pg_data_ss: {}
  conduktor_data_ss: {}
  redpanda-0: {}
  redpanda-1: {}